doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
      master:
        url: '%env(resolve:DATABASE_URL_ROOT)%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '15'

  orm:
    auto_generate_proxy_classes: true
    default_entity_manager: default
    enable_lazy_ghost_objects: true
    entity_managers:
      default:
        connection: default
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
          security_container:
            is_bundle: false
            dir: '%kernel.project_dir%/src/Containers/SecurityContainer/Infrastructure/Data/Doctrine/Entity'
            prefix: 'App\Containers\SecurityContainer\Infrastructure\Data\Doctrine\Entity'
            alias: security_container
          tenant_container:
            is_bundle: false
            dir: '%kernel.project_dir%/src/Containers/TenantContainer/Infrastructure/Data/Doctrine/Entity'
            prefix: 'App\Containers\TenantContainer\Infrastructure\Data\Doctrine\Entity'
            alias: tenant_container
      master:
        connection: master

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
