framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed
    default_bus: 'command.bus'
    buses:
      command.bus: []
      query.bus: []
    transports:
    # failed: 'doctrine://default?queue_name=failed'
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        #options:
        #  use_notify: true
        #  check_delayed_interval: 60000
        retry_strategy:
          max_retries: 3
          multiplier: 2
      sync: 'sync://'

    routing:
      App\Ship\Core\Domain\Command\CommandInterface: sync
      App\Ship\Core\Domain\Query\QueryInterface: sync
      App\Ship\Core\Domain\Message\AsyncMessageInterface: async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
