services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Containers\SecurityContainer\Application\FindsUserInterface:
    alias: App\Containers\SecurityContainer\Infrastructure\Data\Doctrine\Repository\UserRepository
