services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Containers\TenantContainer\Application\FindsTenantInterface:
    alias: App\Containers\TenantContainer\Infrastructure\Data\Doctrine\Repository\TenantRepository

  App\Containers\TenantContainer\Application\PersistsTenantInterface:
    alias: App\Containers\TenantContainer\Infrastructure\Data\Doctrine\Repository\TenantRepository

  App\Containers\TenantContainer\Application\UpdatesTenantInterface:
    alias: App\Containers\TenantContainer\Infrastructure\Data\Doctrine\Repository\TenantRepository
